export default {
  nav: { About: "About", Services: "Services", Team: "Team", Reviews: "Reviews", Contact: "Contact", book: "Book appointment" },
  hero: { eyebrow: "Nova Physiotherapy Speciality Clinic · Addis Ababa", titleA: "Restoring Movement,", titleB: "Renewing Life.", body: "Personalized physiotherapy and rehabilitation designed to reduce pain, restore movement and help you return to daily life.", book: "Book an appointment", inquiry: "Send an inquiry", call: "Call now" },
  trust: { patients: "Human-first care", team: "Experienced clinicians", approach: "Evidence-led plans", hours: "Open Mon–Sat" },
  about: { eyebrow: "The Nova approach", title: "A clearer path back to your life.", body: "Your body is always moving toward balance. At Nova, we combine clinical expertise with attentive, one-to-one care to help you understand your movement, rebuild your confidence and keep doing what matters.", link: "Discover Nova" },
  services: { eyebrow: "Care, shaped around you", title: "From pain to possibility.", body: "Focused care for the moments that change how you move—whether you are recovering, returning to sport or building everyday strength.", items: [{ name: "Pain Management", body: "Thoughtful assessment and targeted treatment for persistent or acute pain." }, { name: "Sports Injury Rehabilitation", body: "Progressive plans that help athletes return to performance with confidence." }, { name: "Post-Operative Rehabilitation", body: "Structured support before and after surgery, at every stage of recovery." }, { name: "Musculoskeletal Physiotherapy", body: "Hands-on and movement-based care for joints, muscles and posture." }, { name: "Neurological Rehabilitation", body: "Patient-led therapy that supports mobility, coordination and independence." }, { name: "Mobility and Strengthening", body: "Practical movement programs for resilience, balance and quality of life." }] },
  why: { eyebrow: "Why Nova", title: "Care that sees the whole person.", points: ["A plan built around your goals, not a template.", "Clear explanations so you know what to do next.", "Small, measurable progress that compounds over time.", "A calm, welcoming clinic designed for focus and trust."] },
  team: { eyebrow: "The people behind your progress", title: "Meet your care team.", roles: ["Senior Physiotherapist and General Manager", "Senior Physiotherapist", "Physiotherapy team"] },
  reviews: { eyebrow: "Patient voices", title: "Movement, made possible.", source: "Selected Google reviews" },
  booking: { eyebrow: "Start your next chapter", title: "Let’s get you moving.", body: "Share a few details and our team will follow up to find the right next step.", appointment: "Book an appointment", inquiry: "General inquiry", name: "Full name", namePlaceholder: "Your name", phone: "Phone number", email: "Email address", service: "Preferred service", select: "Select a service", date: "Preferred date", message: "Message", messagePlaceholder: "Tell us a little about what you need…", submit: "Send request", sending: "Sending…", note: "A real submission endpoint can be connected here later.", success: "Thank you. Your request is ready for the Nova team." },
  contact: { title: "Ready when you are.", body: "Find us at Girar Plaza on the Edna Mall road. Call or WhatsApp the clinic directly for a quick conversation.", call: "Call Nova", addressLabel: "Visit us", directions: "Get directions", hoursLabel: "Opening hours", socialLabel: "Follow along" },
  footer: "Restoring Movement, Renewing Life",
};
